### ISSUE TITLE
bug when working with UITableView with section title displayed.

### ISSUE THREAD

**Issue by simpzan** [samvermette/SVPullToRefresh#29]
when working with table view with section title enabled, and if I scroll down the table view when the SVPullToRefresh is in the loading state, the section title position is buggy.

**Comment by samvermette** [comment]
@simpzan I've been tryin to tackle that issue but haven't found a perfect solution yet. If you hack the scrollView's `contentInset` inside `scrollViewDidScroll:`, the bounce is altered. Feel free to chip in on this.

**Comment by samvermette** [comment]
Fixed with your pull request I merged just now into master.

**Comment by chrischenyc** [comment]
it appears to me that this bug still persists in the latest code. just add following in the Demo/SVViewController.m
- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section
  {
  return @"Section Header";
  }

you will see this:
![Screen Shot 2012-12-17 at 2 26 20 PM](https://f.cloud.github.com/assets/334233/16040/9569633c-47f9-11e2-83e4-59856f54eacc.png)
